### PR TITLE
Adding the Inkeep AI Chat Button

### PR DESCRIPTION
**Pull request by nick-inkeep**
### Description

Adding the Inkeep AI chat button widget per conversation with @asifkazi 

#### Upstream PRs

- 3.10:
- 3.11:
- 3.12:

### CODE REVIEW

**Comment by nick-inkeep** [comment]
Not sure what is needed to get the Netlify preview to work. It works for us when running locally via Docker. Feel free to cherry-pick into your own PR if needed!

**Comment by Simran-B** [comment]
@nick-inkeep It looks like you didn't enable the option to let us push commits to your fork. Can you pull the main branch of arangodb/docs-hugo into this PR, please?

**Comment by nick-inkeep** [comment]
@Simran-B synced the repo. For the CLA, I'm getting a 404 Not Found. Let me know if you need anything there.

**Comment by nerpaula** [comment]
@nick-inkeep I just talked to @asifkazi and looks like the AI bot is needed for the developer hub, not docs. These are separate repos. Please coordinate with him moving forward, I guess this PR is then not relevant here?!

**Comment by nick-inkeep** [comment]
Got it, thanks @nerpaula . We have a version for Developer Hub as well, just don't have permission to make a PR there though (read-only). Will coordinate with Asif. Lets close this one for now.

**Pull request closed without merging**
