### PR TITLE
[DOC-573] Version aliases

### PR DESCRIPTION
**Pull request by dandimeo**
#### Upstream PRs

- 3.10:
- 3.11:
- 3.12:

### CODE REVIEW

**Review by Simran-B — CHANGES_REQUESTED** [review]
Looks mostly good. One thing that doesn't work correctly is if you are on 3.11 and click the copy link to clipboard icon for an HTTP API option, the clipboard content starts with /stable instead of /3.11

**Comment by dandimeo** [comment]
Search version is not found at first page load.

**Comment by dandimeo** [comment]
Search fixed as of last commit

**Review by nerpaula — APPROVED** [review]
LGTM

**Pull request merged**
