### PR TITLE
[DOC-541] api-docs CircleCI Job

### PR DESCRIPTION
**Pull request by dandimeo**
### Description

Integrate api-docs for arangodb/arangodb repository use

- Create api-docs commit CircleCI command
- Implement api-docs commit command as
  - git clone arangodb/api-docs
  - cp generated docs-hugo/site/data/{version}/api-docs.json into api-docs workspace folder
  - git push with tag={tag}

#### Upstream PRs

- 3.10:
- 3.11:
- 3.12:

### CODE REVIEW

**Review by Simran-B — APPROVED** [review]
Based on the visible result at https://github.com/arangodb/api-docs, this LGTM

**Review by nerpaula — APPROVED** [review]

**Pull request merged**
