### PR TITLE
Fix document HTTP API examples

### PR DESCRIPTION
**Pull request by Simran-B**
### Description

Create collection / log response (to be tested)

Example generation requires https://github.com/arangodb/docs-hugo/pull/621 to be merged due to the Batch API removal and the curl examples that failures with v3.12.3+

#### Upstream PRs

- 3.10: 
- 3.11: arangodb/enterprise:3.11.11
- 3.12: arangodb/enterprise-preview:devel-nightly
- 3.13: arangodb/enterprise-preview:devel-nightly

### CODE REVIEW

**Comment by aMahanna** [comment]
Hey @Simran-B! just checking if you pinged me by mistake here? Happy to review, however I don't own this part of documentation

**Comment by Simran-B** [comment]
@aMahanna Yeah, my bad! Please ignore

**Review by apetenchea — APPROVED** [review]

**Pull request merged**
