### PR TITLE
Link style for external and anchor links

### PR DESCRIPTION
**Pull request by Simran-B**
### Description

Use internal link style also for anchor links, as well as for external links. Add icon to external links to indicate that they reference external content and open in a new tab.

Demo: https://deploy-preview-254--docs-hugo.netlify.app/3.11/index-and-search/indexing/working-with-indexes/geo-spatial-indexes/ (note that the GeoJSON anchor link doesn't scroll to the right location but that is addressed by #251 which is part of #232)

#### Upstream PRs

- 3.10:
- 3.11:
- 3.12:

### CODE REVIEW

**Review by dandimeo — COMMENTED** [review]
I don't see any changes in the anchor links?
Anyway LGTM

**Review by nikhil-varma — APPROVED** [review]
Minor change. Approving it considering it will be incorporated. 

Just a suggestion, we should not be handling links that way. It becomes extremely implicit and increases maintenance. Over time we should move to a batter approach. Noting it here just for remembering.

**Comment by Simran-B** [comment]
@dandimeo The changes should look like this, before:

image

After:

image

Note **GeoJSON**, which is an anchor link (only anchor, to go to a different headline on the same page)

@nikhil-varma Yes, I agree that having to set the `link` class for most `<a>` elements to get the right style and the JS link handling is not good. Should we make it the default style and use an event handler for all links and then filter out the few cases where we want a different style/handling?

**Comment by nikhil-varma** [comment]
@Simran-B Styling is OK. What I meant was about the event listener JS function. That felt very implicit and needs a better approach. Can be discussed in a later scope. For now, this is good to go.

**Comment by Simran-B** [comment]
Created a ticket about the link handler: https://arangodb.atlassian.net/browse/DOC-599

**Review by nerpaula — APPROVED** [review]
LGTM

**Pull request merged**
